[build.environment]
  VUE_APP_CONSUMER_KEY = "Your WooCommerce consumer key"
  VUE_APP_CONSUMER_SECRET_KEY = "Your WooCommerce consumer secret key"
[build]
  publish = "dist"
  command = "yarn build"
